---
kind: pipeline
type: digitalocean
name: default

token:
  from_secret: token

server:
  image: docker-18-04
  size: s-1vcpu-1gb
  region: nyc1

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello world!! This is rohit and this is my pipeline installing apache
  - apk add --no-cache sshpass openssh
  - sshpass -p 'iamindian@1Iamindian' ssh -o StrictHostKeyChecking=no root@24.199.127.59 'sudo apt update -y'
  password:
    from_secret: password
  become: true

trigger:
  event:
    - push
    - pull_request
  branch:
    - main